---
title: "R Notebook"
---

```{r setup}
library(tidyverse)
library(impressions)
library(cmcR)
```


```{r}
library(reticulate)
dip <- reticulate::import("diplib")
np <- reticulate::import("numpy")

targFiltered <- target_processed
targFiltered$surface.matrix[is.na(targFiltered$surface.matrix)] <- mean(targFiltered$surface.matrix,na.rm = TRUE)


targFiltered$surface.matrix <- targFiltered$surface.matrix %>%
  dip$VarianceFilter() %>%
  np$asarray()

targFiltered$surface.matrix[is.na(target_processed$surface.matrix)] <- NA

alignedTargetCenters <- comparisonResults_full %>%
  dplyr::select(alignedTargetCell,cellIndex,theta,originalMethod) %>%
  pmap_dfr(~ {
    
    impressions::targetCellCorners(alignedTargetCell = ..1,
                                   cellIndex = ..2,
                                   theta = ..3,
                                   cmcClassif = ..4,
                                   target = target_processed) #%>%
    # group_by(cellIndex,theta,cmcClassif) %>%
    # summarise(x = mean(x),
    #           y = mean(y),
    #           .groups = "drop")
    
  })

targAbs <- target_processed
targAbs$surface.matrix <- abs(targAbs$surface.matrix)

(x3pListPlot(list(target_processed)) +
    geom_point(data = alignedTargetCenters %>%
                 group_by(cellIndex,theta,cmcClassif) %>%
                 summarise(x = mean(x),
                           y = mean(y),
                           .groups = "drop")
               ,
               aes(x=x,y=y),
               inherit.aes = FALSE)) +
  (x3pListPlot(list(targAbs)) +
     geom_point(data = alignedTargetCenters %>%
                  group_by(cellIndex,theta,cmcClassif) %>%
                  summarise(x = mean(x),
                            y = mean(y),
                            .groups = "drop"),
                aes(x=x,y=y),
                inherit.aes = FALSE)) +
  (x3pListPlot(list(targFiltered)) +
     geom_point(data = alignedTargetCenters %>%
                  group_by(cellIndex,theta,cmcClassif) %>%
                  summarise(x = mean(x),
                            y = mean(y),
                            .groups = "drop"),
                aes(x=x,y=y),
                inherit.aes = FALSE))

comparisonResults_full %>%
  filter(comparisonName == "K013sA1 vs. K013sA2") %>%
  dplyr::select(alignedTargetCell,cellIndex,theta,originalMethod) %>%
  pmap_dfr(~ {
    
    impressions::targetCellCorners(alignedTargetCell = ..1,
                                   cellIndex = ..2,
                                   theta = ..3,
                                   cmcClassif = ..4,
                                   target = target_processed) %>%
      group_by(cellIndex,theta,cmcClassif) %>%
      summarise(x = mean(x),
                y = mean(y),
                .groups = "drop")
    
  }) %>%
  group_by(cellIndex) %>%
  group_split() %>%
  map(function(dat){
    
    x3pListPlot(list(targAbs) %>% set_names(unique(dat$cellIndex))) +
      geom_point(data = dat,
                 aes(x=x,y=y),
                 size = 3,
                 inherit.aes = FALSE)
    
  })
```


```{r}
pixelTallies <- alignedTargetCenters %>%
  group_by(x,y) %>%
  tally() %>%
  left_join(targFiltered %>%
              impressions::x3pToDF(),
            by = c("x","y"))

pixelTallies %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x=value,y=n)) +
  geom_jitter() +
  scale_x_log10() +
  geom_smooth(method="lm",se=FALSE)
```

```{r}
cellDifferences %>%
  select(comparisonName,cellIndex,regularCell,absDiff) %>%
  filter(!is.na(absDiff)) %>%
  mutate(cellID = factor(paste0(comparisonName,ifelse(regularCell,", Well-Aligned",", Poorly-Aligned")))) %>%
  # filter(comparisonName == "K013sA1 vs. K002eG1" | cellID == "K013sA1 vs. K013sA2, Well-Aligned") %>%
  ggplot(aes(x=absDiff)) +
  geom_density(aes(fill = cellID),alpha = .5) +
  xlim(c(NA,10)) +
  # geom_vline(xintercept = 0.5745564) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 2,byrow=TRUE))
# geom_vline(xintercept = 0.5018611)
```

```{r}
cellDifferences <- comparisonResults %>%
  mutate(regularCell = (comparisonName == "K013sA1 vs. K013sA2" & 
                          cellIndex %in% c("4, 2","1, 6","2, 7","3, 8","4, 8","8, 4","8, 6"))) %>%
  group_by(comparisonName,regularCell) %>%
  group_split() %>%
  # .[3] %>%
  map_dfr(function(dat){
    
    dat %>%
      select(comparisonName,cellIndex,regularCell,cellHeightValues,alignedTargetCell) %>%
      # slice(1) %>%
      pmap_dfr(~ {
        
        reference <- ..4
        target <- ..5
        
        reference$surface.matrix <- (reference$surface.matrix*reference$cmcR.info$scaleByVal + reference$cmcR.info$centerByVal)*1e6
        target$surface.matrix <- (target$surface.matrix*target$cmcR.info$scaleByVal + target$cmcR.info$centerByVal)*1e6
        
        reference %>%
          impressions::x3pToDF() %>%
          rename(refValue = value) %>%
          left_join(target %>% 
                      impressions::x3pToDF() %>%
                      rename(targValue = value),
                    by = c("x","y")) %>%
          mutate(absDiff = abs(refValue - targValue),
                 comparisonName = ..1,
                 cellIndex = ..2,
                 regularCell = ..3)
        
      })
    
  })
```

```{r}
load("../data/topMatchExampleScans.RData")

topMatchExampleScans %>%
  pull(processedScan) %>%
  map_dbl(~ sd(.$surface.matrix*1e6,na.rm = TRUE))
```



```{r}
ldaFit <- MASS::lda(formula = cellID ~ absDiff,data = cellDifferences %>%
                      select(comparisonName,cellIndex,regularCell,absDiff) %>%
                      filter(!is.na(absDiff)) %>%
                      mutate(cellID = factor(paste0(comparisonName,ifelse(regularCell,", Well-Aligned",", Poorly-Aligned")))) %>%
                      # filter(comparisonName == "K013sA1 vs. K002eG1" | cellID == "K013sA1 vs. K013sA2, Well-Aligned") %>%
                      select(absDiff,comparisonName,cellID))

cellDifferences %>%
  select(comparisonName,cellIndex,regularCell,absDiff) %>%
  filter(!is.na(absDiff)) %>%
  mutate(cellID = factor(paste0(comparisonName,ifelse(regularCell,", Well-Aligned",", Poorly-Aligned")))) %>%
  # filter(comparisonName == "K013sA1 vs. K002eG1" | cellID == "K013sA1 vs. K013sA2, Well-Aligned") %>%
  ggplot(aes(x=absDiff)) +
  geom_rect(data = data.frame(absDiff = seq(0,10,length.out = 10000)) %>%
              mutate(cellID = predict(ldaFit,newdata = data.frame(absDiff = seq(0,10,length.out = 10000)))$class) %>%
              group_by(cellID) %>%
              summarise(xmin = min(absDiff),
                        xmax = max(absDiff),
                        absDiff = 0),
            aes(xmin = xmin,xmax = xmax,fill = cellID,ymin=0,ymax=1),alpha = .2) +
  geom_density(aes(colour = cellID),alpha = .5) +
  xlim(c(NA,10)) +
  # geom_vline(xintercept = 0.5745564) +
  theme(legend.position = "bottom") +
  guides(fill = "none",
         colour = guide_legend(nrow = 2,byrow=TRUE)) +
  coord_cartesian(expand=FALSE) #+
# scale_fill_manual(values = c("#7570b3","#1b9e77","#d95f02"),aesthetics = c("fill","colour"))
# geom_vline(xintercept = 0.5018611)
```


```{r}
library(animation)

comparisonResults  %>%
  filter((cellIndex %in% c("4, 2","1, 6","2, 7","3, 8","4, 8","8, 4","8, 6") & comparisonName == "K013sA1 vs. K013sA2") |
           (cellIndex %in% c("5, 1") & comparisonName == "K013sA1 vs. K002eG1")) %>%
  select(comparisonName,cellIndex,cellHeightValues,alignedTargetCell) %>%
  # slice(1) %>%
  pmap(~ {
    
    reference <- ..3
    target <- ..4
    
    reference$surface.matrix <- (reference$surface.matrix*reference$cmcR.info$scaleByVal + reference$cmcR.info$centerByVal)*1e6
    target$surface.matrix <- (target$surface.matrix*target$cmcR.info$scaleByVal + target$cmcR.info$centerByVal)*1e6
    
    # animation::saveGIF(movie.name = paste0(..1,"_cell",..2,".gif"),expr = {
    
    ret <- map(seq(.25,2.25,by = .5),
               function(tau){
                 
                 patchComparisonPlt <- x3pComparisonPlot(reference = reference,target = target,
                                                         plotNames = c(paste0(..1,"\nReference Cell ",..2),
                                                                       paste0(..1,"\nAligned Target Cell ",..2),
                                                                       # "Element-wise Average","x3p1 diff.","x3p2 diff."
                                                                       paste0("Average, Abs. Diff.\nat most ",tau),
                                                                       paste0("Ref., Abs. Diff.\ngreater than ",tau),
                                                                       paste0("Targ., Abs. Diff\ngreater than ",tau)
                                                         ),
                                                         cutoffThresh = tau,
                                                         unit = "micron")
                 
                 # design <- "ACCD
                 #  BCCE"
                 # 
                 # patchComparisonLegend <- cowplot::plot_grid(patchComparisonPlt$legend$grobs[[1]])
                 # 
                 # patchComparisonPlts_combined <- patchwork::wrap_plots(patchComparisonPlt[[1]],patchComparisonPlt[[2]],patchComparisonPlt[[3]],
                 #                                                       patchComparisonPlt[[4]],patchComparisonPlt[[5]],
                 #                                                       design = design) +
                 # inset_element(patchComparisonLegend,left = -1.7,bottom = 0,right = -1.7,top = 0,on_top = FALSE,align_to = 'full')
                 
                 
                 
                 # plot(patchComparisonPlts_combined)
                 
                 return(patchComparisonPlt[[3]] + patchComparisonPlt[[4]] + patchComparisonPlt[[5]])
                 
               })
    
    # })
    
    ret[[1]] /
      ret[[2]] /
      ret[[3]] +#/
      patchwork::plot_annotation(subtitle = paste0(..1," Cell ",..2),theme = list(plot.subtitle = element_text(hjust = .5)))
    # ret[[4]] /
    # ret[[5]]
    
  })
```


```{r}
blobFeatures <- comparisonResults  %>%
  # filter((cellIndex %in% c("4, 2","1, 6","2, 7","3, 8","4, 8","8, 4","8, 6") & comparisonName == "K013sA1 vs. K013sA2") |
  #          (cellIndex %in% c("5, 1") & comparisonName == "K013sA1 vs. K002eG1")) %>%
  select(comparisonName,cellIndex,cellHeightValues,alignedTargetCell) %>%
  # slice(1) %>%
  pmap_dfr(~ {
    
    # browser()
    
    reference <- ..3
    target <- ..4
    
    reference$surface.matrix <- (reference$surface.matrix*reference$cmcR.info$scaleByVal + reference$cmcR.info$centerByVal)*1e6
    target$surface.matrix <- (target$surface.matrix*target$cmcR.info$scaleByVal + target$cmcR.info$centerByVal)*1e6
    
    # pixelwise average and absolute difference between the two scans
    refTargAverage <- bind_rows(reference %>%
                                  impressions::x3pToDF() %>%
                                  mutate(value = value),
                                target %>%
                                  impressions::x3pToDF() %>%
                                  mutate(value = value)) %>%
      group_by(x,y) %>%
      summarise(valueDiff = abs(diff(value)),
                value = mean(value),
                .groups = "drop")
    
    map_dfr(c(.75,1,1.5,2),
            function(mult){
              
              labeledBlobs <- impressions::labelBlobs(reference,target,
                                                      filterCutoff = mult*sd(c(c(reference$surface.matrix),
                                                                               c(target$surface.matrix)),
                                                                             na.rm = TRUE))
              
              labeledBlobs <- labeledBlobs %>%
                #   mutate(value = factor(value,labels = c("Non-filtered",1:max(labeledBlobs$value,na.rm = TRUE)))) %>%
                rename(blobLabel = value)
              
              nonFilteredObs <- labeledBlobs %>%
                filter(!is.na(blobLabel) & blobLabel > -1)#"Non-filtered")
              
              allObs <- labeledBlobs %>%
                filter(!is.na(blobLabel))
              
              # add to the df created above the pixelwise difference between the reference
              # and average scans. alpha-blend pixels
              refDifference <- reference %>%
                impressions::x3pToDF() %>%
                left_join(refTargAverage %>%
                            rename(aveValue = value),
                          by = c("x","y")) %>%
                mutate(value = ifelse(is.na(aveValue),NA,value)) %>%
                mutate(value = ifelse(value > mult*sd(c(c(reference$surface.matrix),
                                                                               c(target$surface.matrix)),
                                                                             na.rm = TRUE),
                                      value,NA))
              
              targDifference <- target %>%
                impressions::x3pToDF() %>%
                left_join(
                  refTargAverage %>%
                    rename(aveValue = value),
                  by = c("x","y")) %>%
                mutate(value = ifelse(is.na(aveValue),NA,value)) %>%
                mutate(value = ifelse(value > mult*sd(c(c(reference$surface.matrix),
                                                                               c(target$surface.matrix)),
                                                                             na.rm = TRUE),
                                      value,NA))
              
              data.frame(comparisonName = ..1,
                         cellIndex = ..2,
                         sdMultiplier = mult,
                         sdValue = sd(c(c(reference$surface.matrix),
                                        c(target$surface.matrix)),
                                      na.rm = TRUE)) %>%
                mutate(differenceCor_nonStandardized = cor(refDifference$value,
                                                           targDifference$value,
                                                           use = "pairwise.complete.obs"),
                       blobSize_ave_nonStandardized = nonFilteredObs %>%
                         group_by(blobLabel) %>%
                         tally() %>%
                         pull(n) %>%
                         mean(na.rm = TRUE),
                       blobSize_sd_nonStandardized = nonFilteredObs %>%
                         group_by(blobLabel) %>%
                         tally() %>%
                         pull(n) %>%
                         sd(na.rm = TRUE))
              
            })
    
  })

```

```{r}
blobFeatures %>%
  mutate(rowID = paste0(comparisonName,cellIndex)) %>%
  ggplot(aes(x = sdMultiplier,y = blobSize_ave_nonStandardized)) +
  geom_line(aes(colour = comparisonName,group = rowID))
```

```{r}
source("../code/fiveplot.r")

reference_processed <- x3ptools::x3p_read("../data/K013sA1_processed.x3p")
target_processed <- x3ptools::x3p_read("../data/K013sA2_processed.x3p")

fullScan_comparisonData <- map_dfr(seq(-30,30,by = 3),
        function(theta){

          reference_processed %>%
  comparison_allTogether(target = target_processed,
                         theta = theta,
                         numCells = c(1,1),
                         maxMissingProp = .99,
                         sideLengthMultiplier = 1.1,
                         returnX3Ps = TRUE)

        }) %>%
  # filter(fft_ccf == max(fft_ccf)) %>%
  mutate(comparisonName = "K013sA1 vs. K013sA2")
```

```{r}
animation::saveGIF({walk(seq(-30,30,by = 3),
                         function(theta){
                           dat <-  reference_processed %>%
                             comparison_allTogether(target = target_processed,
                                                    theta = theta,
                                                    numCells = c(1,1),
                                                    maxMissingProp = .99,
                                                    sideLengthMultiplier = 1.1,
                                                    returnX3Ps = TRUE) %>%
                             mutate(comparisonName = "K013sA1 vs. K013sA2")
                           
                           plt <- fiveplot(comparisonResults = dat,referenceScan = "K013sA1",targetScan = "K013sA2",cell = "1, 1")
                           
                           plt[[2]] <- plt[[2]] +
                             labs(subtitle = paste0("K013sA2 Aligned Cell\nat ",unique(dat$theta),"°"))
                           
                           plot(plt)
                         })},movie.name = "~/this-is-us/images/cartridge_cases/4-22-22_spotlight/fullScanFivePlot.gif")
```

```{r}
walk(3,
                         function(theta){
                           dat <-  reference_processed %>%
                             comparison_allTogether(target = target_processed,
                                                    theta = theta,
                                                    numCells = c(1,1),
                                                    maxMissingProp = .99,
                                                    sideLengthMultiplier = 1.1,
                                                    returnX3Ps = TRUE) %>%
                             mutate(comparisonName = "K013sA1 vs. K013sA2")
                           
                           plt <- fiveplot(comparisonResults = dat,referenceScan = "K013sA1",targetScan = "K013sA2",cell = "1, 1")
                           
                           plt[[2]] <- plt[[2]] +
                             labs(subtitle = paste0("K013sA2 Aligned Cell\nat ",unique(dat$theta),"°"))
                           
                           plot(plt)
                           
                           ggsave(plot = plt,filename = "~/this-is-us/images/cartridge_cases/4-22-22_spotlight/fullScan_optimalAlignment.png")
                         })
```

```{r}
debugonce(impressions::labelBlobs)
impressions::labelBlobs(reference_processed,target_processed,filterCutoff = sd(c(c(reference_processed$surface.matrix),
                                                                                 c(target_processed$surface.matrix)),na.rm = TRUE))

numColors <- dat %>%
  as.data.frame() %>%
      filter(value >= 0) %>%
      pull(value) %>%
      unique() %>%
      length()

colorScheme <- sample(RColorBrewer::brewer.pal(12,"Paired"),size = numColors,replace = TRUE)

dat %>%
  as.data.frame() %>%
  mutate(value = ifelse(value > 0,1,0)) %>%
      mutate(value = factor(value)) %>%
      ggplot(aes(x=x,y=y,fill = value)) +
      geom_raster() +
      coord_fixed(expand = FALSE) +
      theme_void() +
      theme(legend.position = "none",
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            plot.subtitle = element_text(hjust = .5,size=8),
            plot.margin = margin(1,.15,0,.15,"cm")) +
      scale_fill_manual(values = c("black","white"),
                        na.value = "gray65") +
      labs(subtitle = "Filtered Elements")

dat %>%
  as.data.frame() %>%
      mutate(value = factor(value)) %>%
      ggplot(aes(x=x,y=y,fill = value)) +
      geom_raster() +
      coord_fixed(expand = FALSE) +
      theme_void() +
      theme(legend.position = "none",
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            plot.subtitle = element_text(hjust = .5,size=8),
            plot.margin = margin(1,.15,0,.15,"cm")) +
      scale_fill_manual(values = c("black",colorScheme),
                        na.value = "gray65") +
      labs(subtitle = "Labeled Filtered\nNeighborhoods")
```

